### ISSUE TITLE
Allow automatic posting to discord webook every tick

### ISSUE THREAD

**Issue by Greymagic27** [aussig/BGS-Tally#118] opened 2023-06-11 11:48 UTC
After a tick has happened for the BGS, automaticly post your BGS activity to the discord webhook you've set up. If EDMC is not open, then post to the discord webhook as soon as EDMC opens, and a tick has occured.

**Comment by aussig** [comment] 2023-06-11 17:43
Thank you for taking time to post this suggestion, but it is a duplicate of #61 so closing this one.

**Closed** 2023-06-12 08:30 UTC
Labels: duplicate, enhancement
