### ISSUE TITLE
Menu is missing in new EDMC update under settings.

### ISSUE THREAD

**Issue by Docaston** [aussig/BGS-Tally#268] opened 2024-09-25 18:55 UTC
**Describe the bug**
Menu is missing in new EDMC update under settings.

**To Reproduce**
1. Go to settings
3. Click on...not in the menu.
4. Scroll down to 'N/A'
5. "See error"

**Expected behavior**
When you open settings BGS tally is not there.

**Screenshots**
![BGS tally missing](https://github.com/user-attachments/assets/627cb6fc-681c-4cf3-a428-34e0194bae93)

**Desktop (please complete the following information):**
 - OS: WIn 10
 - Plugin Version V4.0.1
 - EDMC Version 5.12.0+cc6e200
**Log Files**
Please attach the following three log files:

1. [EDMarketConnector-debug.log](https://github.com/user-attachments/files/17137037/EDMarketConnector-debug.log)

2. [EDMarketConnector.log](https://github.com/user-attachments/files/17137042/EDMarketConnector.log)

3. [Journal.2024-09-25T112226.01.log](https://github.com/user-attachments/files/17137235/Journal.2024-09-25T112226.01.log)

**Additional context**
Updated EDMC and its missing, thats all I know.

**Comment by aussig** [comment] 2024-09-25 20:30
This was caused by a change in EDMC. I released a beta of BGS-Tally earlier today that fixes the problem. Download it manually from the releases section, or wait for the final release which I’ll try to get out tomorrow.

**Comment by Docaston** [comment] 2024-09-25 22:53
Ah I didn't see that. I figured you knew about it but as there were no
issues otherwise I wasn't sure. Thanks

**Comment by aussig** [comment] 2024-09-26 16:57
Closed in https://github.com/aussig/BGS-Tally/commit/f5566afb4dc327c86c156e02c7909834ac9c9092

**Closed by aussig** 2024-09-26 16:57 UTC
Labels: bug
